const data = {
  donor: [
    {
      _id: "01",
      name: "A.S.S.M.Q-E-Elahy",
      age: 24,
      bloodGroup: "O+",
      lastDonate: "22/04/21",
      address: "Fatullah, Narayanganj",
      mobile: "01913093116",
      email: "scoutelahy@gmail.com",
      image: "./images/elahy.jpg",
    },

    {
      _id: "02",
      name: "Faheem Hussain",
      age: 25,
      bloodGroup: "A+",
      lastDonate: "02/09/20",
      address: "Amlapara, Narayanganj",
      email: "faheemhussain545@gmail.com",
      mobile: "01930102284",
      image: "./images/faheem.jpg",
    },
    {
      _id: "03",
      name: "Fardeen Ahmed Ifty",
      age: 24,
      bloodGroup: "O+",
      lastDonate: "07/07/21",
      address: "Don Chamber, Narayanganj",
      mobile: "01672395420",
      email: "ahmedfardeen0@gmail.com",
      image: "",
    },
    {
      _id: "04",
      name: "Mehedi Hasan Sabbir",
      age: 24,
      bloodGroup: "A+",
      lastDonate: "08/08/21",
      address: "Jatrabari, Dhaka",
      mobile: "01515248245",
      email: "mahadisabbir.ms@gmail.com",
      image: "./images/MehediSabbir.jpg",
    },
    {
      _id: "05",
      name: "Faheem",
      age: 24,
      bloodGroup: "A+",
      lastDonate: "22/04/21",
      address: "Narayanganj",
      mobile: "01841551123",
      image: "",
    },
    {
      _id: "06",
      name: "Faheem",
      age: 24,
      bloodGroup: "A+",
      lastDonate: "22/04/21",
      address: "Narayanganj",
      mobile: "01841551123",
      image: "",
    },
    {
      _id: "07",
      name: "Faheem",
      age: 24,
      bloodGroup: "A+",
      lastDonate: "22/04/21",
      address: "Narayanganj",
      mobile: "01841551123",
      image: "",
    },
    {
      _id: "08",
      name: "Faheem",
      age: 24,
      bloodGroup: "A+",
      lastDonate: "22/04/21",
      address: "Narayanganj",
      mobile: "01841551123",
      image: "",
    },
    {
      _id: "09",
      name: "Faheem",
      age: 24,
      bloodGroup: "A+",
      lastDonate: "22/04/21",
      address: "Narayanganj",
      mobile: "01841551123",
      image: "",
    },
    {
      _id: "10",
      name: "Faheem",
      age: 24,
      bloodGroup: "A+",
      lastDonate: "22/04/21",
      address: "Narayanganj",
      mobile: "01841551123",
      image: "",
    },
    {
      _id: "11",
      name: "Faheem",
      age: 24,
      bloodGroup: "A+",
      lastDonate: "22/04/21",
      address: "Narayanganj",
      mobile: "01841551123",
      image: "",
    },
    {
      _id: "12",
      name: "Faheem",
      age: 24,
      bloodGroup: "A+",
      lastDonate: "22/04/21",
      address: "Narayanganj",
      mobile: "01841551123",
      image: "",
    },
    {
      _id: "13",
      name: "Faheem",
      age: 24,
      bloodGroup: "A+",
      lastDonate: "22/04/21",
      address: "Narayanganj",
      mobile: "01841551123",
      image: "",
    },
    {
      _id: "14",
      name: "Faheem",
      age: 24,
      bloodGroup: "A+",
      lastDonate: "22/04/21",
      address: "Narayanganj",
      mobile: "01841551123",
      image: "",
    },
  ],
};

export default data;
